---
# In development environment a user with same name as your system user will be created
system_administrators:
  - name: daniel
    ssh_key: "../pub_keys/daniel.pub"
    state: present
  - name: enrico
    ssh_key: "../pub_keys/enricostn.pub"
    state: present
  - name: pau
    ssh_key: "../pub_keys/pau.pub"
    state: present

# Let's Encrypt conf
certificate_authority_email:

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: true
