---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  become: yes
  vars:
    htpasswd_file: /etc/nginx/htpasswd.users
  roles:

  - role: geerlingguy.security

  - role: geerlingguy.java
    vars:
      java_packages:
        - openjdk-8-jre

  - role: geerlingguy.elasticsearch
    environment:
      # Putting the quotes around true is important here because, as ansible is python, it likes to pass true as True and the install script expects a lowercase true.
      ES_SKIP_SET_KERNEL_PARAMETERS: "true"

  - role: geerlingguy.logstash
    tags: logstash

  - role: geerlingguy.kibana

  # We need install Python3 passlib library first of htpasswd because is a requirement. In Python2 is already installed, but to Python3 needs be installed.
  - role: passlib

  - role: geerlingguy.htpasswd
    vars:
      htpasswd_credentials:
        - path: "{{ htpasswd_file }}"
          name: "{{ kibana_admin }}"
          password: "{{ kibana_password }}"
          owner: root
          group: root
          mode: "u+rw,g+r"

  - name: coopdevs.certbot_nginx
    vars:
      domain_name: "{{ inventory_hostname }}"
      letsencrypt_email: "{{ certificate_authority_email }}"
      certbot_nginx_cert_name: "{{ inventory_hostname }}"
    when: not development_environment

  - role: jdauphant.nginx
    when: not development_environment
