---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  become: yes
  become_user: root
  vars:
    htpasswd_file: /etc/nginx/htpasswd.users
  roles:
  - role: java
  - role: elasticsearch
  - role: kibana
  - role: metricbeat
  - role: geerlingguy.htpasswd
    vars:
      htpasswd_credentials:
        - path: "{{ htpasswd_file }}"
          name: "{{ kibana_admin }}"
          password: "{{ kibana_password }}"
          owner: root
          group: root
          mode: "u+rw,g+r"

  - role: jdauphant.nginx
    vars:
      nginx_sites:
       kibana:
         - listen 80
         - server_name "{{ inventory_hostname }}"
         - auth_basic "Restricted Access"
         - auth_basic_user_file "{{ htpasswd_file }}"
         - location / {
             proxy_pass http://localhost:5601;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection 'upgrade';
             proxy_set_header Host $host;
             proxy_cache_bypass $http_upgrade;
           }

